//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerBilly.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carstouser
    {
        public int ID { get; set; }
        public Nullable<int> Car_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual createcarmodel createcarmodel { get; set; }
        public virtual createusermodel createusermodel { get; set; }
    }
}
